name: Publish NeatInput (branch 'master')
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish NuGet packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push NeatInput.Windows package
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/NeatInput.Windows/NeatInput.Windows.csproj
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: NeatInput.Windows

      - name: Push NeatInput.Linux package
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/NeatInput.Linux/NeatInput.Linux.csproj
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: NeatInput.Linux