name: Publish NeatInput (branch 'master')
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish NeatInput.Windows
        uses: rohith/publish-nuget@v2.3.0
        with: 
          PROJECT_FILE_PATH: src/NeatInput.Windows/NeatInput.Windows.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: NeatInput.Windows
